# default configuration
baseURL = "/"
languageCode = "en-us"
summaryLength = "10"
theme = "kross-hugo-custom"
title = "Klub mladih Split"

# css plugins
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"

[[params.plugins.css]]
URL = "plugins/slick/slick.css"

[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"


# js plugin
[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"

[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"

[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"

[[params.plugins.js]]
URL = "plugins/shuffle/shuffle.min.js"


# menu
[[menu.main]]
URL = "about"
name = "O nama"
weight = 2

[[menu.main]]
URL = "blog"
name = "Blog"
weight = 3

[[menu.main]]
URL = "portfolio"
name = "Projekti"
weight = 4

[[menu.main]]
URL = "contact"
name = "Kontakti"
weight = 5


# default parameters
[params]
home = "Početna"
logo = "images/logo/logo_127x40.png"
# theme color
theme_color = "#1db0f4"
# contact info
# phone = ""
email = "klubmladih.split@gmail.com"
address = "Split, Hrvatska"
# meta description
author = "Klub mladih Split"
description = "Ovo je web stranica Kluba mladih Split"
# google analitycs
google_analitycs_id = "Your ID"
# copyright
copyright = "Copyright &copy; 2020 Klub mladih Split"


# contact
[params.contact]
enable = false
form_action = "#" # contact form works with : https://formspree.io

# preloader
[params.preloader]
enable = true
preloader = "" # use png, jpg, svg or gif format

# social site
[[params.social]]
URL = "https://www.facebook.com/klubmladihsplit"
icon = "ti-facebook"

[[params.social]]
URL = "https://www.instagram.com/klub_mladih_split/"
icon = "ti-instagram"

[[params.social]]
URL = "https://www.youtube.com/channel/UCfx3T_Rk7XicWfD5_PT9qzw"
icon = "ti-youtube"

[[params.social]]
URL = "https://www.twitter.com/klubmladihsplit"
icon = "ti-twitter-alt"
